"""Would another tuning objective have picked another model? v2's own 100 trials, ranked four ways.

The search is rerun with v2's objective and seed and must land on v2's stored parameters first.
Each objective's pick is refitted on the training years and scored on the holdout, which is
reported, not used to choose.
"""

from __future__ import annotations

import argparse
import json
import logging
import math
import sys
from pathlib import Path
from typing import Any

import pandas as pd

from tfire.config import Config, load_config, setup_logging
from tfire.evaluation import bootstrap_scores, scores
from tfire.features.registry import load_registry
from tfire.models.trentino import (
    OBJECTIVES,
    SPECS,
    design_matrix,
    fit_holdout,
    training_mask,
    tune,
)
from tfire.report import table

logger = logging.getLogger("tuning_objectives")

REPORT_FILENAME = "tuning_objectives.md"
EXPERIMENT = "tuning_objectives"
REFERENCE = "v2"
TUNED_ON = "pooled_auprc"


def reference_tuning(config: Config) -> dict[str, Any]:
    path = config.path(config.paths.trentino_model_dir) / REFERENCE / "metrics.json"
    tuning: dict[str, Any] = json.loads(path.read_text(encoding="utf-8"))["tuning"]
    return tuning


def reproduced(stored: dict[str, Any], rerun: dict[str, Any]) -> bool:
    """Same best trial, same rounds, same parameters to float precision."""
    if stored["rounds"] != rerun["rounds"] or set(stored["params"]) != set(rerun["params"]):
        return False
    return all(
        math.isclose(float(stored["params"][name]), float(rerun["params"][name]), rel_tol=1e-12)
        for name in stored["params"]
    )


def rank(trials: list[dict[str, Any]]) -> pd.DataFrame:
    """Every trial's value under every objective, larger better."""
    return pd.DataFrame(
        {
            name: [objective(trial["pooled_auprc"], trial["folds"]) for trial in trials]
            for name, objective in OBJECTIVES.items()
        },
        index=pd.Index([trial["number"] for trial in trials], name="trial"),
    )


def holdout(
    config: Config,
    trial: dict[str, Any],
    data: tuple[pd.DataFrame, Any, Any],
) -> dict[str, Any]:
    features, labels, train = data
    _, _, probabilities = fit_holdout(
        SPECS["xgboost"],
        features,
        labels,
        train,
        config,
        {"params": trial["params"], "rounds": trial["rounds"]},
    )
    return {
        **scores(labels[~train], probabilities),
        "intervals": bootstrap_scores(
            labels[~train],
            probabilities,
            config.evaluation.bootstrap_resamples,
            config.project.random_seed,
        ),
    }


def render(results: dict[str, Any]) -> str:
    values: pd.DataFrame = results["values"]
    picks: dict[str, dict[str, Any]] = results["picks"]
    trials = {trial["number"]: trial for trial in results["trials"]}
    names = list(OBJECTIVES)
    lines = [
        "# Tuning objective",
        "",
        "Generated by `scripts/tuning_objectives.py`. The Optuna search was rerun on 1984-2014 "
        f"with `{TUNED_ON}` and the stored seed, "
        f"{len(trials)} trials, recording each trial's per-fold scores. "
        + (
            "It reproduces v2's best trial exactly (parameters and rounds), so the table below "
            "is v2's own search."
            if results["reproduced"]
            else "**It does not reproduce v2's best trial**: the table is a new search, not v2's."
        ),
        "",
        "Candidates, all read so that larger is better:",
        "",
        "- `pooled_auprc`: AUPRC of the out-of-fold predictions pooled over the five year "
        "blocks. What v1 and v2 were tuned on.",
        "- `fold_lift`: mean over the blocks of AUPRC divided by the block's prevalence.",
        "- `fold_logloss`: mean over the blocks of the log-loss with each class weighted to one "
        "half, negated.",
        "- `fold_auroc`: mean over the blocks of AUROC, a control that ignores precision.",
        "",
        "## Prevalence by block",
        "",
    ]
    first = trials[picks[TUNED_ON]["trial"]]
    lines += table(
        ["block", "rows", "prevalence"],
        [
            [fold["years"], fold["rows"], f"{100 * fold['positive_rate']:.1f}%"]
            for fold in first["folds"]
        ],
    )
    lines += [
        "",
        "Pooling weighs the early blocks, where positives are four to five times as frequent.",
        "",
        "## The trial each objective picks",
        "",
    ]
    lines += table(
        [
            "objective",
            "trial",
            "rounds",
            *(f"{name}" for name in names),
            "holdout AUPRC (95% CI)",
            "holdout AUROC",
            "holdout lift",
        ],
        [
            [
                f"`{name}`",
                pick["trial"],
                trials[pick["trial"]]["rounds"],
                *(f"{values.loc[pick['trial'], other]:.4f}" for other in names),
                f"{pick['holdout']['auprc']:.4f} "
                f"({pick['holdout']['intervals']['auprc']['lo']:.3f}-"
                f"{pick['holdout']['intervals']['auprc']['hi']:.3f})",
                f"{pick['holdout']['auroc']:.4f}",
                f"{pick['holdout']['lift']:.2f}",
            ]
            for name, pick in picks.items()
        ],
    )
    lines += ["", "## Parameters of the picked trials", ""]
    params = list(first["params"])
    lines += table(
        ["objective", *params],
        [
            [
                f"`{name}`",
                *(
                    f"{trials[pick['trial']]['params'][key]:.4g}"
                    if isinstance(trials[pick["trial"]]["params"][key], float)
                    else str(trials[pick["trial"]]["params"][key])
                    for key in params
                ),
            ]
            for name, pick in picks.items()
        ],
    )
    lines += ["", "## How far the objectives agree", ""]
    spearman = values.rank().corr()
    lines += table(
        ["", *names],
        [[f"`{a}`", *(f"{spearman.loc[a, b]:.2f}" for b in names)] for a in names],
    )
    lines += [
        "",
        "Spearman correlation of the four values over all trials.",
        "",
        "## Reading",
        "",
    ]
    distinct = {pick["trial"] for pick in picks.values()}
    tuned = picks[TUNED_ON]["trial"]
    if len(distinct) == 1:
        lines.append(
            "Every objective picks the same trial: the objective was not what limited v2, and "
            "a new search can keep it."
        )
    else:
        lift = picks["fold_lift"]
        lines.append(
            f"The objectives disagree ({len(distinct)} distinct trials). `fold_lift` picks trial "
            f"{lift['trial']} where `{TUNED_ON}` picked {tuned}; on the holdout that is "
            f"{lift['holdout']['auprc'] - picks[TUNED_ON]['holdout']['auprc']:+.4f} AUPRC and "
            f"{lift['holdout']['auroc'] - picks[TUNED_ON]['holdout']['auroc']:+.4f} AUROC. "
            "The holdout intervals overlap whenever these differences are below about 0.05 "
            "AUPRC, so the choice rests on the argument (a ranking that does not favor the "
            "years with the most positives), not on the holdout."
        )
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", type=Path, default=None)
    args = parser.parse_args(argv)

    config = load_config(args.config)
    setup_logging(config)
    config = config.model_copy(
        update={"trentino": config.trentino.model_copy(update={"tuning_objective": TUNED_ON})}
    )

    frame = pd.read_parquet(config.path(config.paths.dataset_out))
    features, labels, years = design_matrix(frame, load_registry())
    stored = reference_tuning(config)
    train = training_mask(years, config)

    rerun = tune(features.loc[train], labels[train], years.loc[train], config)
    trials: list[dict[str, Any]] = rerun.pop("trial_table")
    same = reproduced(stored, rerun)
    logger.info("Rerun %s v2's best trial", "reproduces" if same else "does NOT reproduce")

    values = rank(trials)
    by_number = {trial["number"]: trial for trial in trials}
    picks: dict[str, dict[str, Any]] = {}
    for name in OBJECTIVES:
        number = int(values[name].idxmax())
        picks[name] = {
            "trial": number,
            "holdout": holdout(config, by_number[number], (features, labels, train)),
        }
        logger.info(
            "%-13s picks trial %d, holdout AUPRC %.4f",
            name,
            number,
            picks[name]["holdout"]["auprc"],
        )

    directory = config.path(config.paths.trentino_model_dir) / "experiments" / EXPERIMENT
    directory.mkdir(parents=True, exist_ok=True)
    (directory / "trials.json").write_text(
        json.dumps(
            {"reproduced": same, "tuning": rerun, "trials": trials, "picks": picks}, indent=2
        ),
        encoding="utf-8",
    )

    results = {"reproduced": same, "trials": trials, "values": values, "picks": picks}
    out = config.path(config.paths.report_dir) / REPORT_FILENAME
    out.write_text(render(results), encoding="utf-8")
    logger.info("Wrote %s", out)
    return 0


if __name__ == "__main__":
    sys.exit(main())
